services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - 80:80
    volumes:
      - ./{CARPETA_DEL_PROYECTO}:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mysql
      - php
    networks:
      - laravel-nginx-docker_laravel

  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel-nginx-docker_laravel

  php:
    container_name: php
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./{CARPETA_DEL_PROYECTO}:/var/www/html
    networks:
      - laravel-nginx-docker_laravel

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel-nginx-docker_laravel

  #  grafana:
#    image: grafana/grafana:latest
#    container_name: grafana
#    volumes:
#      - ./{CARPETA_DEL_PROYECTO}:/var/www/html
#      - ./config/grafana.ini:/etc/grafana/grafana.ini
#      - ./grafana:/var/lib/grafana
#    ports:
#      - "3000:3000"
#    depends_on:
#      - php
#      - mysql
#    networks:
#      - laravel-nginx-docker_laravel

  composer:
    container_name: composer
    build:
      context: .
      dockerfile: composer.dockerfile
    volumes:
      - ./{CARPETA_DEL_PROYECTO}:/var/www/html
    depends_on:
      - php
    working_dir: /var/www/html
    networks:
      - laravel-nginx-docker_laravel

  npm:
    image: node:current-alpine
    container_name: npm
    volumes:
      - ./{CARPETA_DEL_PROYECTO}:/var/www/html
    entrypoint: ["npm"]
    working_dir: /var/www/html

  artisan:
    container_name: artisan
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./{CARPETA_DEL_PROYECTO}:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - laravel-nginx-docker_laravel

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - laravel-nginx-docker_laravel

networks:
  laravel-nginx-docker_laravel:
    driver: bridge